// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYi5C4FohwProyewhKBNEj4_AEyzz9-PQ',
    appId: '1:900985734708:web:752d66040534dc5bdbac61',
    messagingSenderId: '900985734708',
    projectId: 'tulpar-19a6c',
    authDomain: 'tulpar-19a6c.firebaseapp.com',
    storageBucket: 'tulpar-19a6c.firebasestorage.app',
    measurementId: 'G-TKFVGBVC2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9PI8R0PJ83IFgQpimCJwoZEllZ5WlNw8',
    appId: '1:900985734708:android:cfde5640105e498adbac61',
    messagingSenderId: '900985734708',
    projectId: 'tulpar-19a6c',
    storageBucket: 'tulpar-19a6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfKVbxO44-os7-z0x4NbBOIDkADdSiX1s',
    appId: '1:900985734708:ios:2be74ec22b95e383dbac61',
    messagingSenderId: '900985734708',
    projectId: 'tulpar-19a6c',
    storageBucket: 'tulpar-19a6c.firebasestorage.app',
    iosClientId: '900985734708-0marnc3vng0rsmcoe2dknjrmoq8s9du8.apps.googleusercontent.com',
    iosBundleId: 'com.example.tulparFront',
  );
}
